name: deploy
on: [push]
env: 
    TESTNET_PRIV_KEY: ${{ secrets.TESTNET_PRIV_KEY }}
    TESTNET_APP_PRIV_KEY: ${{ secrets.TESTNET_APP_PRIV_KEY }}
jobs:
  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - run: npm install -g near-cli
      - run: mkdir -p ~/.near-credentials/testnet
      - run: echo $TESTNET_APP_PRIV_KEY > ~/.near-credentials/testnet/app2.hashassine.testnet.json
      - run: echo $TESTNET_PRIV_KEY > ~/.near-credentials/testnet/hashassine.testnet.json
      - run: make contract/build
      - run: make contract/deploy-testnet

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: cd hashassine-frontend && npm ci
      - run: make frontend/build
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: hashassine-frontend/dist/hashassine-frontend